# https://travis-ci.org/ryanss/holidays.py

language: python

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy

install:
    - python setup.py install
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install coverage
    - pip install codeclimate-test-reporter

script:
    - coverage run test.py test

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION != 3.2 ]]; then coveralls; fi
